//
// Created by TedHuang on 2023/11/23.
//

#ifndef LVILIBUVCCAMERAPROJECT_LIBUVCCAMERA_H
#define LVILIBUVCCAMERAPROJECT_LIBUVCCAMERA_H

typedef jlong ID_TYPE;
#define LOCAL_DEBUG 1


#endif //LVILIBUVCCAMERAPROJECT_LIBUVCCAMERA_H
